[package]
authors = ["Adam Gian <contact@adamgian.com>"]
edition = "2021"
license = "Apache-2.0"
name = "minify_selectors"
version = "0.9.15"


[[bin]]
name = "minify-selectors"
path = "./src/main.rs"


[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
globwalk = "0.8.1"

parse_selectors = { path = "../parse_selectors" }
encode_selector = { path = "../encode_selector" }
