[package]
name = "minify-selectors"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs62 = "0.1.4"
globwalk = "0.8.1"
onig = "6.3.1"
structopt = "0.3.25"
