[package]
name = "minify-selectors"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globwalk = "0.8.1"
regex = "1.5.4"
structopt = "0.3.25"
