[package]
license = "Apache-2.0"
version = "0.8.0"


[workspace]

members = [
	"crates/encode_selector",
	"crates/minify_selectors",
	"crates/parse_selectors",
]


[profile.release]
codegen-units = 1
lto = true
strip = true
