[package]
authors = ["Adam Gian <contact@adamgian.com>"]
edition = "2021"
name = "parse_selectors"
version = "0.6.8"


[dependencies]
lazy_static = "1.4.0"
onig = "6.3.1"

encode_selector = { path = "../encode_selector" }
