a.querySelectorAll("#a");
b.querySelectorAll('#b');
c.querySelectorAll(`#c`);
d.querySelectorAll(".d");
e.querySelectorAll('.e');
f.querySelectorAll(`.f`);
g.querySelectorAll( ".g" );
h.querySelectorAll( '.h' );
i.querySelectorAll( `.i` );
j.querySelectorAll( " .j " );
k.querySelectorAll( ' .k ' );
l.querySelectorAll( ` .l ` );

m.querySelectorAll(".m .d");
n.querySelectorAll('.n .d');
o.querySelectorAll(`.o .d`);
p.querySelectorAll("div.p .d");
q.querySelectorAll('div.q .d');
r.querySelectorAll(`div.r .d`);
s.querySelectorAll("div.s .p");
t.querySelectorAll('div.t .q');
u.querySelectorAll(`div.u .r`);

v.querySelectorAll(".v[href$=.org]");
w.querySelectorAll('.w[href$=.org]');
x.querySelectorAll(`.x[href$=.org]`);
y.querySelectorAll(".y[href$=\".com.au\"]");
z.querySelectorAll('.z[href$=\'.com.au\']');
A.querySelectorAll(`.A[href$=\'.com.au\']`);
B.querySelectorAll(".B[href$='.org' s]");
C.querySelectorAll('.C[href$=".org" s]');
D.querySelectorAll(`.D[href$='.org' s]`);
E.querySelectorAll(".E[aria-labelledby=F]");
F.querySelectorAll('.G[aria-labelledby=F]');
G.querySelectorAll(`.H[aria-labelledby=F]`);
H.querySelectorAll(".I[aria-labelledby=\"F\"]");
I.querySelectorAll('.J[aria-labelledby=\'F\']');
J.querySelectorAll(`.K[aria-labelledby=\'F\']`);
K.querySelectorAll(".L[aria-labelledby='F' s]");
L.querySelectorAll('.M[aria-labelledby="F" s]');
M.querySelectorAll(`.N[aria-labelledby='F' s]`);
