document.getElementsByClassName("SELECTOR-1");
document.getElementsByClassName('SELECTOR-2');
document.getElementsByClassName(`SELECTOR-3`);
document.getElementsByClassName( "SELECTOR-4" );
document.getElementsByClassName( 'SELECTOR-5' );
document.getElementsByClassName( `SELECTOR-6` );
document.getElementsByClassName("SELECTOR-7 SELECTOR-1");
document.getElementsByClassName('SELECTOR-8 SELECTOR-1');
document.getElementsByClassName(`SELECTOR-9 SELECTOR-1`);
document.getElementsByClassName("SELECTOR-10 > SELECTOR-1");
document.getElementsByClassName('SELECTOR-11 > SELECTOR-1');
document.getElementsByClassName(`SELECTOR-12 > SELECTOR-1`);
document.getElementsByClassName("SELECTOR-10 + SELECTOR-1");
document.getElementsByClassName('SELECTOR-11 + SELECTOR-1');
document.getElementsByClassName(`SELECTOR-12 + SELECTOR-1`);
document.getElementsByClassName("SELECTOR-10 ~ SELECTOR-1");
document.getElementsByClassName('SELECTOR-11 ~ SELECTOR-1');
document.getElementsByClassName(`SELECTOR-12 ~ SELECTOR-1`);
