a.querySelectorAll("#SELECTOR-1");
b.querySelectorAll('#SELECTOR-2');
c.querySelectorAll(`#SELECTOR-3`);
d.querySelectorAll(".SELECTOR-4");
e.querySelectorAll('.SELECTOR-5');
f.querySelectorAll(`.SELECTOR-6`);
g.querySelectorAll( ".SELECTOR-7" );
h.querySelectorAll( '.SELECTOR-8' );
i.querySelectorAll( `.SELECTOR-9` );
j.querySelectorAll( " .SELECTOR-10 " );
k.querySelectorAll( ' .SELECTOR-11 ' );
l.querySelectorAll( ` .SELECTOR-12 ` );

m.querySelectorAll(".SELECTOR-13 .SELECTOR-4");
n.querySelectorAll('.SELECTOR-14 .SELECTOR-4');
o.querySelectorAll(`.SELECTOR-15 .SELECTOR-4`);
p.querySelectorAll("div.SELECTOR-16 .SELECTOR-4");
q.querySelectorAll('div.SELECTOR-17 .SELECTOR-4');
r.querySelectorAll(`div.SELECTOR-18 .SELECTOR-4`);
s.querySelectorAll("div.SELECTOR-19 .SELECTOR-16");
t.querySelectorAll('div.SELECTOR-20 .SELECTOR-17');
u.querySelectorAll(`div.SELECTOR-21 .SELECTOR-18`);

v.querySelectorAll(".SELECTOR-22[href$=.org]");
w.querySelectorAll('.SELECTOR-23[href$=.org]');
x.querySelectorAll(`.SELECTOR-24[href$=.org]`);
y.querySelectorAll(".SELECTOR-25[href$=\".com.au\"]");
z.querySelectorAll('.SELECTOR-26[href$=\'.com.au\']');
A.querySelectorAll(`.SELECTOR-27[href$=\'.com.au\']`);
B.querySelectorAll(".SELECTOR-28[href$='.org' s]");
C.querySelectorAll('.SELECTOR-29[href$=".org" s]');
D.querySelectorAll(`.SELECTOR-30[href$='.org' s]`);
E.querySelectorAll(".SELECTOR-31[aria-labelledby=SELECTOR-4]");
F.querySelectorAll('.SELECTOR-32[aria-labelledby=SELECTOR-4]');
G.querySelectorAll(`.SELECTOR-33[aria-labelledby=SELECTOR-4]`);
H.querySelectorAll(".SELECTOR-34[aria-labelledby=\"SELECTOR-4\"]");
I.querySelectorAll('.SELECTOR-35[aria-labelledby=\'SELECTOR-4\']');
J.querySelectorAll(`.SELECTOR-36[aria-labelledby=\'SELECTOR-4\']`);
K.querySelectorAll(".SELECTOR-37[aria-labelledby='SELECTOR-4' s]");
L.querySelectorAll('.SELECTOR-38[aria-labelledby="SELECTOR-4" s]');
M.querySelectorAll(`.SELECTOR-39[aria-labelledby='SELECTOR-4' s]`);

N.querySelectorAll(foo);
O.querySelectorAll( bar );
P.querySelectorAll(foo.bar);
Q.querySelectorAll( foo.bar );
